import type { CmsContent } from './types';

export const SEED: CmsContent = {
  version: 1,
  updatedAt: '',
  projects: [
    {
      id: 'PROJECT_002',
      slug: 'deephq',
      name: 'DeepHQ',
      shortDescription: 'A digital marketing website presenting social media management and Meta Ads services, with a reviews page and a WhatsApp order enquiry form.',
      fullDescription: 'DeepHQ is an AI-powered digital marketing agency website. It presents social media management and Meta Ads services, a reviews page, and a WhatsApp order enquiry form.',
      client: 'DeepHQ',
      projectUrl: 'https://www.deephq.online',
      githubUrl: '',
      technologies: ['Marketing Website', 'Service Pages', 'Reviews', 'WhatsApp Enquiries'],
      category: 'Marketing Website',
      coverImageId: '',
      visualType: 'deephq',
      status: 'live',
      featured: true,
      published: true,
      order: 0,
    },
  ],
  products: [
    {
      id: 'PRODUCT_001',
      name: 'Business ERP suite',
      description: 'Operations, inventory, and administration in one connected system.',
      imageId: '',
      category: 'ERP',
      status: 'coming_soon',
      pricing: '',
      demoUrl: '',
      productUrl: '',
      featured: false,
      published: true,
      order: 0,
    },
    {
      id: 'PRODUCT_002',
      name: 'Reserved',
      description: 'A slot for the next product Devzard is preparing for businesses.',
      imageId: '',
      category: 'ERP',
      status: 'coming_soon',
      pricing: '',
      demoUrl: '',
      productUrl: '',
      featured: false,
      published: true,
      order: 1,
    },
  ],
  services: [
    { id: 'websites', name: 'Websites', shortDescription: 'Fast, modern websites designed around your brand and your customers.', fullDescription: 'A website should make your business easier to understand and easier to choose. We start with your audience, design a clear experience, and build a fast, accessible site you can actually maintain.', features: ['Business websites', 'Landing pages', 'Portfolio websites', 'Corporate websites'], cta: 'Explore Websites', deliverables: 'Custom design, responsive development, a content management setup when needed, technical SEO, and production deployment.', icon: 'globe', visual: 'websites', published: true, order: 0 },
    { id: 'ecommerce', name: 'Ecommerce', shortDescription: 'Complete online stores built for real products, customers, and orders.', fullDescription: 'From the first product to the final order, every part of your store should work together. We connect the storefront, payments, stock, and back-office workflows around the way you sell.', features: ['Product management', 'Orders and customers', 'Admin dashboards', 'Payments', 'Inventory'], cta: 'Explore Ecommerce', deliverables: 'A custom storefront, product catalog, secure checkout integration, order management, and an administration workspace.', icon: 'bag', visual: 'ecommerce', published: true, order: 1 },
    { id: 'business', name: 'Business Software', shortDescription: 'Custom systems that replace spreadsheets, disconnected tools, and manual workflows.', fullDescription: 'Good internal software gets out of the way. We map your existing operations and build one reliable system with the right permissions, reporting, and workflows for your team.', features: ['ERP systems', 'CRM', 'School management', 'Inventory systems', 'Dashboards'], cta: 'Explore Business Software', deliverables: 'Workflow discovery, data modeling, role-based access, custom modules, reporting, and a practical migration plan.', icon: 'grid', visual: 'business', published: true, order: 2 },
    { id: 'custom', name: 'Custom Applications', shortDescription: "If your business needs software that doesn't exist yet, we build it.", fullDescription: 'A specific problem deserves a considered solution. We turn requirements into a focused product, build the important things first, and leave room for the product to grow.', features: ['SaaS platforms', 'Internal tools', 'Web applications', 'Client portals', 'Custom dashboards'], cta: 'Build Something Custom', deliverables: 'Product architecture, interface design, frontend and backend development, integrations, testing, and deployment.', icon: 'code', visual: 'custom', published: true, order: 3 },
    { id: 'ai', name: 'AI & Automation', shortDescription: "Use AI where it creates real leverage, not just because it's trendy.", fullDescription: 'We look for repetitive work, disconnected data, and slow handoffs. Then we build focused automations with clear boundaries, human oversight, and results you can evaluate.', features: ['AI assistants', 'Workflow automation', 'API integrations', 'Intelligent search', 'Business automation'], cta: 'Explore AI', deliverables: 'An opportunity assessment, a working proof of concept, integrated workflows, monitoring, and clear documentation.', icon: 'spark', visual: 'ai', published: true, order: 4 },
  ],
  technologies: [
    { id: 'tech-react', name: 'React', category: 'Frontend', icon: 'code', description: 'Interface development for web applications.', published: true, order: 0 },
    { id: 'tech-node', name: 'Node.js / Spring Boot', category: 'Backend', icon: 'terminal', description: 'Application servers chosen according to the product.', published: true, order: 1 },
    { id: 'tech-pg', name: 'PostgreSQL', category: 'Database', icon: 'database', description: 'Relational data for business systems.', published: true, order: 2 },
    { id: 'tech-git', name: 'GitHub', category: 'Version control', icon: 'git', description: 'Source control and collaboration.', published: true, order: 3 },
  ],
  team: [
    { id: 'team-hadi', name: 'Abdul Hadi', role: 'CEO & Founder', biography: '', imageId: '', initials: 'AH', github: '', linkedin: '', x: '', published: true, order: 0 },
    { id: 'team-fazi', name: 'Fazi', role: 'Co-Founder', biography: '', imageId: '', initials: 'F', github: '', linkedin: '', x: '', published: true, order: 1 },
    { id: 'team-talha', name: 'Talha', role: 'Co-Founder', biography: '', imageId: '', initials: 'T', github: '', linkedin: '', x: '', published: true, order: 2 },
  ],
  testimonials: [],
  homepage: {
    heroBrand: 'devzard',
    heroHeadline: 'We build software that',
    heroHeadlineAccent: 'moves businesses forward.',
    heroSubtitle: 'Websites, ecommerce platforms, business systems, and custom software. Designed, built, and shipped by Devzard.',
    heroCta: 'Start a Project',
    heroCtaLink: '/#contact',
    heroSecondary: 'See Our Work',
    heroSecondaryLink: '/#work',
    principles: [
      { id: 'p1', title: 'Built for your business', description: "We don't force your business into a template. We build around the way you actually work.", icon: 'target' },
      { id: 'p2', title: 'From idea to production', description: 'From the first wireframe to deployment, Devzard handles the complete development process.', icon: 'layers' },
      { id: 'p3', title: 'Small team. Serious output.', description: 'Direct communication, fast iteration, and engineering without unnecessary layers.', icon: 'bolt' },
    ],
    processTitle: 'From idea to shipped.',
    processSubtitle: 'Six steps. No hand-offs between departments — the same people carry the project from the first call to production.',
    processSteps: [
      { id: 'ps1', n: '01', title: 'Discover', text: 'Understand the business, users, requirements, and goals.', meta: 'requirements.md' },
      { id: 'ps2', n: '02', title: 'Design', text: 'Turn requirements into architecture, flows, and interface designs.', meta: 'schema · flows · ui' },
      { id: 'ps3', n: '03', title: 'Build', text: 'Develop the product using modern technologies and clean architecture.', meta: 'git commit -m "feat"' },
      { id: 'ps4', n: '04', title: 'Test', text: 'Test functionality, responsiveness, performance, and edge cases.', meta: '48 passed · 0 failed' },
      { id: 'ps5', n: '05', title: 'Launch', text: 'Deploy the product and configure the production environment.', meta: 'DEPLOYED → prod' },
      { id: 'ps6', n: '06', title: 'Grow', text: 'Maintenance, improvements, analytics, new features, and ongoing support.', meta: 'v2.0 → v2.14' },
    ],
    finalCtaLabel: 'Good software starts with a conversation',
    finalCtaTitle: 'Have an idea?',
    finalCtaAccent: "Let's build it.",
    finalCtaText: "Tell us what you're trying to build. We'll figure out the technology.",
    finalCtaButton: 'Start a Project',
    finalCtaSecondary: 'Contact Devzard',
  },
  settings: {
    siteName: 'Devzard',
    email: 'devzardpk@gmail.com',
    phone: '+92 317 4541414',
    address: '',
    github: '',
    linkedin: '',
    x: '',
    seoTitle: 'Devzard — Software Built for Businesses',
    seoDescription: 'Devzard builds modern websites, ecommerce platforms, business software, custom applications, and AI-powered solutions.',
    ogImage: '/images/devzard-social.jpg',
    footerText: 'Software built for businesses that want to move forward.',
    logoImageId: '',
    faviconImageId: '',
  },
};
