import { useState } from 'react';
import { processSteps } from '../data/site';
import { SiteLink } from '../lib/navigation';
import { Dashboard } from '../components/Dashboard';
import { StorefrontMockup } from '../components/Work';
import { Icon, Reveal, SectionLabel } from '../components/ui';

const contents = [
  ['overview', 'Overview'], ['challenge', 'The challenge'], ['solution', 'The solution'], ['features', 'Key features'], ['technology', 'Technology'], ['interface', 'The interface'], ['development', 'Development'], ['results', 'The outcome'],
];

export default function CaseStudy() {
  const [preview, setPreview] = useState<'storefront' | 'admin'>('storefront');
  return <>
    <section className="case-hero"><div className="container"><SiteLink href="/#work" className="back-link"><Icon name="arrow-left" size={15} />Back to selected work</SiteLink><div className="case-hero-content"><div><SectionLabel>DEVZARD / PROJECT_001</SectionLabel><h1>Alwazir<span>.</span></h1></div><div><p className="case-hero-tagline">One storefront.<br />One connected business.</p><p className="case-hero-description">A custom wholesale ecommerce platform that brings products, customers, and operations together.</p><span className="case-project-type mono">ECOMMERCE PLATFORM / CUSTOM WEB APPLICATION</span></div></div></div></section>
    <div className="case-cover"><div className="container"><StorefrontMockup /><p className="case-preview-note">Illustrative storefront presentation. Product photography and catalog content are used for demonstration.</p></div></div>
    <div className="container case-layout"><aside className="case-toc"><p className="section-label">IN THIS PROJECT</p><nav aria-label="Case study contents">{contents.map(([id, title], index) => <a key={id} href={`#case-${id}`}><span>0{index + 1}</span>{title}</a>)}</nav><SiteLink href="/#contact" className="text-link">Build with Devzard<Icon name="arrow-up" size={14} /></SiteLink></aside><article className="case-article">
      <Reveal><section id="case-overview" className="case-section"><SectionLabel>01 / Project overview</SectionLabel><h2>Commerce, without<br />the disconnect.</h2><p>Alwazir is a modern wholesale ecommerce platform with product management, customer workflows, orders, administration, and a customizable storefront.</p><p>The idea is simple: the customer-facing experience and the systems behind it should work as one product, not a collection of disconnected tools.</p><dl className="case-facts"><div><dt>PRODUCT</dt><dd>Wholesale ecommerce</dd></div><div><dt>SCOPE</dt><dd>Storefront + administration</dd></div><div><dt>APPROACH</dt><dd>Custom development</dd></div></dl></section></Reveal>
      <Reveal><section id="case-challenge" className="case-section"><SectionLabel>02 / The challenge</SectionLabel><h2>More than a storefront.</h2><p>The client needed a modern wholesale storefront that could manage products, customers, and orders without relying on disconnected systems.</p><p>A polished website was only one part of the problem. The business also needed a practical way to keep its catalog organized, follow orders through their lifecycle, and give administrators a clear view of daily work.</p><blockquote>Build the experience customers see.<br /><span>And the system the business actually needs.</span></blockquote></section></Reveal>
      <Reveal><section id="case-solution" className="case-section"><SectionLabel>03 / The solution</SectionLabel><h2>One connected workspace.</h2><p>Devzard built a custom ecommerce platform with a dedicated administration system and customizable storefront. Shared product, order, and customer data connects the two experiences.</p><div className="architecture-diagram" role="img" aria-label="The customer storefront and admin workspace both connect to a shared application API, which connects to product, order, and customer data."><div className="architecture-clients"><div><Icon name="globe" size={24} /><strong>Storefront</strong><span>The customer experience</span></div><div><Icon name="grid" size={24} /><strong>Admin workspace</strong><span>The business operations</span></div></div><div className="architecture-connectors"><i /><i /></div><div className="architecture-api"><Icon name="code" size={21} /><div><strong>Application API</strong><span>One connected application layer</span></div><span className="mono">Node.js</span></div><div className="architecture-trunk" /><div className="architecture-data"><Icon name="database" size={20} /><span>Products</span><i /><span>Orders</span><i /><span>Customers</span></div></div></section></Reveal>
      <Reveal><section id="case-features" className="case-section"><SectionLabel>04 / Key features</SectionLabel><h2>Made for the whole workflow.</h2><div className="case-feature-grid">{[{ title: 'Product management', text: 'Manage the catalog, categories, pricing, and product information from one workspace.', icon: 'box' as const }, { title: 'Order workflows', text: 'Follow orders through a clear lifecycle, with customer and product details connected.', icon: 'bag' as const }, { title: 'Customer management', text: 'Keep customer records and their order context together.', icon: 'users' as const }, { title: 'Admin dashboard', text: 'A focused interface for the people running the business every day.', icon: 'chart' as const }, { title: 'Customizable storefront', text: 'A flexible customer-facing experience that fits the brand and its catalog.', icon: 'globe' as const }, { title: 'A connected platform', text: 'Shared application logic and data instead of repeated manual updates.', icon: 'layers' as const }].map(feature => <div key={feature.title}><Icon name={feature.icon} size={21} /><h3>{feature.title}</h3><p>{feature.text}</p></div>)}</div></section></Reveal>
      <Reveal><section id="case-technology" className="case-section"><SectionLabel>05 / Technology</SectionLabel><h2>Clear boundaries.<br />Connected underneath.</h2><p>A Node.js application layer connects the storefront and administration experience. Separating the interface from business logic makes it easier to evolve each part without losing the connection between them.</p><div className="case-tech-list"><div><span>INTERFACE</span><strong>Responsive web application</strong></div><div><span>APPLICATION</span><strong>Node.js</strong></div><div><span>OPERATIONS</span><strong>Dedicated admin workspace</strong></div><div><span>DATA</span><strong>Products, orders, and customers</strong></div></div></section></Reveal>
      <section id="case-interface" className="case-section case-interface"><Reveal><SectionLabel>06 / The interface</SectionLabel><h2>Look around. It works.</h2><p>Explore the storefront presentation or switch to the interactive admin preview. Try a different section, open an order, or export a sample report.</p></Reveal><div className="preview-tabs" role="tablist" aria-label="Alwazir interface preview"><button role="tab" id="tab-storefront" aria-selected={preview === 'storefront'} aria-controls="preview-storefront" tabIndex={preview === 'storefront' ? 0 : -1} onClick={() => setPreview('storefront')} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); setPreview('admin'); document.getElementById('tab-admin')?.focus(); } }}><Icon name="globe" size={15} />Storefront</button><button role="tab" id="tab-admin" aria-selected={preview === 'admin'} aria-controls="preview-admin" tabIndex={preview === 'admin' ? 0 : -1} onClick={() => setPreview('admin')} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); setPreview('storefront'); document.getElementById('tab-storefront')?.focus(); } }}><Icon name="grid" size={15} />Admin workspace</button><span className="mono">ILLUSTRATIVE PREVIEW</span></div><div className="case-interactive-preview" role="tabpanel" id={`preview-${preview}`} aria-labelledby={`tab-${preview}`} tabIndex={0}>{preview === 'storefront' ? <StorefrontMockup showProducts /> : <Dashboard compact />}</div><p className="fine-print">The UI presentation uses sample products, customers, and transactions. It does not expose a live client environment.</p></section>
      <Reveal><section id="case-development" className="case-section"><SectionLabel>07 / Development process</SectionLabel><h2>Built in clear steps.</h2><p>Our approach keeps the important decisions visible, from understanding the business to preparing the product for production.</p><ol className="case-process">{processSteps.map((step, index) => <li key={step.title}><span className="mono">0{index + 1}</span><div><h3>{step.title}</h3><p>{step.detail}</p></div></li>)}</ol></section></Reveal>
      <Reveal><section id="case-results" className="case-section case-results"><SectionLabel>08 / The outcome</SectionLabel><h2>A connected foundation.</h2><p>A storefront and business workspace designed to work together, with a clear foundation for the product to grow.</p><ul>{['One place for products, customers, and order workflows.', 'A customizable storefront connected to business operations.', 'A product that can evolve as requirements change.'].map(result => <li key={result}><Icon name="check" size={18} />{result}</li>)}</ul><p className="fine-print">No business performance statistics are claimed in this case study. The focus is the platform, its scope, and the workflow it supports.</p></section></Reveal>
    </article></div>
    <section className="case-next"><Reveal className="container"><SectionLabel>Your requirements. Your product.</SectionLabel><h2>Have something similar in mind?</h2><p>Let's figure out what your business needs, and build it properly.</p><div><SiteLink className="button button-primary" href="/#contact">Start a Project<Icon name="arrow" size={17} /></SiteLink><SiteLink className="text-link" href="/#work">Back to our work<Icon name="arrow-left" size={16} /></SiteLink></div></Reveal></section>
  </>;
}