import { processSteps } from '../data/site';
import { SiteLink } from '../lib/navigation';
import { DeepHQMockup } from '../components/Work';
import { Icon, Reveal, SectionLabel } from '../components/ui';

const LIVE_URL = 'https://www.deephq.online';

const contents = [
  ['overview', 'Overview'], ['challenge', 'The challenge'], ['solution', 'The solution'], ['features', 'What the site does'], ['technology', 'Technology'], ['interface', 'The live site'], ['development', 'Development'], ['results', 'The outcome'],
];

export default function DeepHQCaseStudy() {
  return <>
    <section className="case-hero"><div className="container"><SiteLink href="/#work" className="back-link"><Icon name="arrow-left" size={15} />Back to selected work</SiteLink><div className="case-hero-content"><div><SectionLabel>DEVZARD / PROJECT_002</SectionLabel><h1>DeepHQ<span>.</span></h1></div><div><p className="case-hero-tagline">Marketing, measured<br />in real time.</p><p className="case-hero-description">A website for an AI-powered digital marketing agency. It shows the work, explains the services, and turns visitors into orders.</p><span className="case-project-type mono">MARKETING WEBSITE / LIVE AT DEEPHQ.ONLINE</span></div></div><a href={LIVE_URL} target="_blank" rel="noopener noreferrer" className="button button-quiet case-hero-visit">Visit deephq.online<Icon name="external" size={16} /></a></div></section>
    <div className="case-cover case-cover-deephq"><div className="container"><DeepHQMockup /><p className="case-preview-note">Presentation of the live DeepHQ site, using the content and palette shown on deephq.online. Campaign metrics are the client's own live figures.</p></div></div>
    <div className="container case-layout"><aside className="case-toc"><p className="section-label">IN THIS PROJECT</p><nav aria-label="Case study contents">{contents.map(([id, title], index) => <a key={id} href={`#case-${id}`}><span>0{index + 1}</span>{title}</a>)}</nav><a href={LIVE_URL} target="_blank" rel="noopener noreferrer" className="text-link case-toc-live">Visit the live site<Icon name="external" size={13} /></a><SiteLink href="/#contact" className="text-link">Build with Devzard<Icon name="arrow-up" size={14} /></SiteLink></aside><article className="case-article">
      <Reveal><section id="case-overview" className="case-section"><SectionLabel>01 / Project overview</SectionLabel><h2>Proof before<br />the pitch.</h2><p>DeepHQ is an AI-powered digital marketing agency that manages social media accounts and runs Meta Ads campaigns for measurable growth. This project is the agency's own website: a front door that explains the service and starts the conversation.</p><dl className="case-facts"><div><dt>PRODUCT</dt><dd>Agency website</dd></div><div><dt>LIVE AT</dt><dd>deephq.online</dd></div><div><dt>SCOPE</dt><dd>Design, build &amp; launch</dd></div></dl></section></Reveal>
      <Reveal><section id="case-challenge" className="case-section"><SectionLabel>02 / The challenge</SectionLabel><h2>Sell performance, not promises.</h2><p>A marketing agency's website has to do two jobs at once: prove the capability, and convert the visitor. A generic template makes it hard to show what an AI-driven team actually does day to day.</p><p>The site needed to feel current and technical, show real campaign indicators, and give visitors a direct path to order.</p><blockquote>Show the numbers.<br /><span>Then make ordering effortless.</span></blockquote></section></Reveal>
      <Reveal><section id="case-solution" className="case-section"><SectionLabel>03 / The solution</SectionLabel><h2>One focused page,<br />one clear action.</h2><p>Devzard designed and built a focused site instead of a deep one. A positioning hero leads with the outcome, a live campaign snapshot carries the proof, the three service areas are laid out plainly, and an order form sends enquiries straight to the team.</p><p>The result is a site a prospect can understand in seconds and act on without hunting for a contact form.</p></section></Reveal>
      <Reveal><section id="case-features" className="case-section"><SectionLabel>04 / What the site does</SectionLabel><h2>Built to convert.</h2><div className="case-feature-grid">{[{ title: 'Live campaign snapshot', text: 'Return on ad spend, followers growth, and cost per lead, presented with a trend chart before the visitor scrolls.', icon: 'chart' as const }, { title: 'Performance statistics', text: 'Brands managed, ad spend optimized, average ROAS, and 24/7 AI monitoring in a clear stats band.', icon: 'spark' as const }, { title: 'Clear service areas', text: 'Social media management, Meta Ads management, and AI analytics & insights, each explained in plain language.', icon: 'grid' as const }, { title: 'Direct order flow', text: 'An order form that collects name, email, business, and channel details and sends the enquiry straight to the team.', icon: 'bolt' as const }, { title: 'Reviews page', text: 'A space for real feedback from the brands DeepHQ works with.', icon: 'users' as const }, { title: 'Free AI audit offer', text: 'A low-friction reason to start: order a plan and get a free AI audit of your social accounts.', icon: 'target' as const }].map(feature => <div key={feature.title}><Icon name={feature.icon} size={21} /><h3>{feature.title}</h3><p>{feature.text}</p></div>)}</div></section></Reveal>
      <Reveal><section id="case-technology" className="case-section"><SectionLabel>05 / Technology</SectionLabel><h2>Lightweight by choice.</h2><p>The site is a fast, static web application. No heavy framework, no framework-driven bloat — just clean HTML, CSS, and JavaScript doing exactly what the brand needs.</p><div className="case-tech-list"><div><span>FRONTEND</span><strong>HTML · CSS · JavaScript</strong></div><div><span>TYPOGRAPHY</span><strong>Inter (Google Fonts)</strong></div><div><span>BRAND SYSTEM</span><strong>Deep blue, #030A1C → #0A8CFF</strong></div><div><span>HOSTING</span><strong>Vercel</strong></div></div></section></Reveal>
      <section id="case-interface" className="case-section case-interface"><Reveal><SectionLabel>06 / The live site</SectionLabel><h2>It's not a mockup.<br />It's live.</h2><p>The DeepHQ website is running in production. This preview loads the actual site; the full version, including the order flow, is one click away.</p></Reveal><div className="live-site-frame"><div className="browser-bar"><div className="window-dots" aria-hidden="true"><i /><i /><i /></div><div className="browser-address"><Icon name="shield" size={11} /><span>deephq.online</span></div><span className="browser-demo"><i className="status-dot" />Live site</span></div><iframe src={LIVE_URL} title="DeepHQ live website" loading="lazy" /></div><div className="live-site-note"><span>Preview loads deephq.online in a secure frame. If it doesn't render in your browser, use the button below.</span><a href={LIVE_URL} target="_blank" rel="noopener noreferrer" className="button button-quiet live-site-button">Visit deephq.online<Icon name="external" size={16} /></a></div></section>
      <Reveal><section id="case-development" className="case-section"><SectionLabel>07 / Development process</SectionLabel><h2>Built in clear steps.</h2><p>Our approach keeps the important decisions visible, from understanding the business to preparing the product for production.</p><ol className="case-process">{processSteps.map((step, index) => <li key={step.title}><span className="mono">0{index + 1}</span><div><h3>{step.title}</h3><p>{step.detail}</p></div></li>)}</ol></section></Reveal>
      <Reveal><section id="case-results" className="case-section case-results"><SectionLabel>08 / The outcome</SectionLabel><h2>A front door that works.</h2><p>The site is live and doing the job: positioning the brand, showing the numbers, and giving visitors a direct line to order.</p><ul>{['A live, production website at deephq.online.', 'Campaign indicators shown before the visitor has to ask.', 'A simple order path from first click to first conversation.'].map(result => <li key={result}><Icon name="check" size={18} />{result}</li>)}</ul><p className="fine-print">Campaign metrics quoted in this case study are the client's own content, shown on the live website. Devzard makes no independent claims about them.</p></section></Reveal>
    </article></div>
    <section className="case-next"><Reveal className="container"><SectionLabel>Another build from the same team.</SectionLabel><h2>See how custom commerce gets built.</h2><p>Alwazir — a wholesale ecommerce platform with a storefront and a connected admin workspace.</p><div><SiteLink className="button button-primary" href="/work/alwazir">View the Alwazir case study<Icon name="arrow" size={17} /></SiteLink><SiteLink className="text-link" href="/#work">Back to our work<Icon name="arrow-left" size={16} /></SiteLink></div></Reveal></section>
  </>;
}
