import { useState } from 'react';
import { faqItems } from '../data/site';
import { useContent } from '../cms/context';
import { telHref } from '../cms/types';
import { downloadFile, SiteLink } from '../lib/navigation';
import { Icon, Reveal, SectionLabel } from '../components/ui';

const notes = [
  { id: 'a-smaller-first-release', category: 'PRODUCT THINKING', title: 'Your first version should do less.', intro: 'A focused first release is not a compromise. It is how you learn what actually matters.', paragraphs: ['It is easy to describe a finished product. It is harder, and more useful, to identify the smallest complete workflow that helps a real person do a real job.', 'Start there. If you are building an inventory system, receiving an item, updating stock, and finding it again might matter more than a sophisticated reporting suite. Make that workflow reliable before adding a dozen adjacent features.', 'Smaller scope does not mean lower quality. Accessibility, understandable errors, dependable data, and a usable interface belong in the first release. An ambitious feature list does not.', 'Write down what the release needs to prove. Build enough to test that. Then use what you learn to decide what belongs in the next version.'] },
  { id: 'when-to-build-custom', category: 'BUSINESS SOFTWARE', title: 'When does custom software make sense?', intro: 'Not every problem needs a new application. Here is how we think about the decision.', paragraphs: ['Start by checking whether an existing tool already solves the problem well. A mature product with a sensible subscription is often a better choice than maintaining a bespoke system.', 'Custom software starts to make sense when your workflow is central to how the business operates and existing tools consistently get in the way. Repeated manual work, fragile integrations, and duplicate data entry are useful signals.', 'Compare the full cost of both options. Custom development includes discovery, implementation, hosting, maintenance, and future changes. Existing tools come with their own costs: subscriptions, workarounds, migration, and the limits of what you can control.', 'The answer may be a combination: a small custom application that connects reliable existing services. The goal is not to build everything. It is to make the business work better.'] },
  { id: 'deployment-is-not-the-finish-line', category: 'ENGINEERING', title: 'Deployment is not the finish line.', intro: 'The most important environment is the one your customers actually use.', paragraphs: ['A successful build tells you the code can be packaged. It does not tell you that the production environment is ready for customers.', 'Before launch, verify the configuration, secrets, domain, backups, monitoring, and critical user journeys. Test the workflows against the actual services they will use. Make sure failures are visible to someone who can act on them.', 'Write down how to deploy, how to roll back, and how to get help. A useful handover is more than a repository link. It gives the business and the next developer enough context to look after the product.', 'After launch, pay attention to the places where people hesitate or need help. Real usage will show you opportunities that no amount of planning can completely predict.'] },
];

export default function ResourcePage({ kind }: { kind: string }) {
  const { content } = useContent();
  const CONTACT_EMAIL = content.settings.email;
  const CONTACT_PHONE = content.settings.phone;
  const CONTACT_PHONE_HREF = telHref(CONTACT_PHONE);
  const briefTemplate = `DEVZARD / PROJECT BRIEF\n\nYour name:\nYour email:\nCompany:\n\n1. What does your business do?\n\n2. What problem are you trying to solve?\n\n3. Who will use this product?\n\n4. What should someone be able to do in the first version?\n\n5. Do you have an existing website, software, or data to work with?\n\n6. Are there services we need to connect to?\n\n7. What is your estimated budget and timeline?\n\n8. What would a successful outcome look like?\n\nSend your brief to ${CONTACT_EMAIL}.\nPhone: ${CONTACT_PHONE}\n`;
  const [openNote, setOpenNote] = useState<string | null>(null);
  const isPrivacy = kind === 'privacy';
  const isTerms = kind === 'terms';
  const title = kind === 'faq' ? 'A few good questions.' : kind === 'blog' ? 'Notes from the build.' : isPrivacy ? 'Your privacy, clearly.' : isTerms ? 'A few ground rules.' : 'Working with Devzard.';
  const subtitle = kind === 'faq' ? 'Straight answers about projects, process, and working together.' : kind === 'blog' ? 'Practical thinking about building software that earns its place.' : isPrivacy ? 'What this website collects, what it does not, and how to get in touch.' : isTerms ? 'The terms for using this website. Project work is covered by a separate agreement.' : 'A practical guide to getting a project started and keeping it on track.';
  return <div className={`resource-page${isPrivacy || isTerms ? ' legal-page' : ''}`}><div className="container"><SiteLink className="back-link" href="/"><Icon name="arrow-left" size={15} />Back to Devzard</SiteLink><header className="resource-header"><SectionLabel>{isPrivacy || isTerms ? 'DEVZARD / LEGAL' : `DEVZARD / ${kind.toUpperCase()}`}</SectionLabel><h1>{title}</h1><p>{subtitle}</p></header>
    {kind === 'faq' && <div className="faq-list">{faqItems.map((item, index) => <Reveal key={item.question} delay={Math.min(index * 40, 160)}><details><summary><span className="mono">0{index + 1}</span><h2>{item.question}</h2><Icon name="plus" size={19} /></summary><p>{item.answer}</p></details></Reveal>)}</div>}
    {kind === 'blog' && <div className="notes-list">{notes.map((note, index) => <article key={note.id} className={`note${openNote === note.id ? ' is-open' : ''}`}><button className="note-toggle" onClick={() => setOpenNote(openNote === note.id ? null : note.id)} aria-expanded={openNote === note.id} aria-controls={note.id}><span className="mono note-number">0{index + 1}</span><span><span className="note-category mono">{note.category}</span><span className="note-title">{note.title}</span><span className="note-intro">{note.intro}</span></span><Icon name={openNote === note.id ? 'close' : 'arrow-up'} size={24} /></button><div id={note.id} className="note-content" hidden={openNote !== note.id}>{note.paragraphs.map(paragraph => <p key={paragraph.slice(0, 30)}>{paragraph}</p>)}</div></article>)}</div>}
    {kind === 'documentation' && <div className="documentation-layout"><div className="docs-content"><section><SectionLabel>01 / Before we start</SectionLabel><h2>A useful brief, not a perfect one.</h2><p>You do not need a technical specification to start a conversation. A clear description of the problem is much more useful than a list of technologies.</p><ul><li>Tell us what your business does and who the product is for.</li><li>Describe the workflow you want to improve, including what is frustrating today.</li><li>List the essential things the first version must do.</li><li>Share your budget range, timing, and any existing tools or data.</li></ul><button className="button button-quiet" onClick={() => downloadFile('devzard-project-brief-template.txt', briefTemplate)}>Download brief template<Icon name="download" size={16} /></button></section><section><SectionLabel>02 / During development</SectionLabel><h2>Keep the feedback loop short.</h2><p>We agree on a scope and milestones before implementation. Working previews make it easier to evaluate the product while there is still time to improve it.</p><ul><li>Choose a main point of contact for decisions and feedback.</li><li>Collect feedback in one place, with examples where possible.</li><li>Separate a defect from a new requirement. Both matter, but they affect planning differently.</li><li>Keep account ownership and access clear from the start.</li></ul></section><section><SectionLabel>03 / At handover</SectionLabel><h2>Know what you are taking over.</h2><p>A useful handover explains the product and how it runs. The specific deliverables and support arrangements are set out in your project agreement.</p><ul><li>Source code access and a guide to the project structure.</li><li>Environment configuration and deployment instructions.</li><li>Ownership of hosting, domains, and third-party accounts.</li><li>A walkthrough, known limitations, and an agreed support plan.</li></ul></section></div><aside className="docs-aside"><Icon name="terminal" size={27} /><h3>A starting point.</h3><p>The project brief template asks the questions that help us understand your business. Fill in what you know. Leave the rest for the conversation.</p><button className="text-link" onClick={() => downloadFile('devzard-project-brief-template.txt', briefTemplate)}>Get the template<Icon name="download" size={15} /></button><span className="mono">PLAIN TEXT / NO SIGN-UP</span></aside></div>}
    {isPrivacy && <div className="legal-content"><p className="legal-updated mono">WEBSITE PRIVACY NOTICE / 2026</p><section><h2>Project inquiries</h2><p>The inquiry form on this website prepares an email draft on your device. It does not send your information to a form server or save a submitted request. Your details remain in the current page's memory until you leave or refresh it.</p><p>If you choose to send the email, your name, contact information, and project brief will be shared with Devzard through your email provider. We use correspondence to understand your request and communicate with you about it.</p></section><section><h2>Cookies and analytics</h2><p>This website does not set advertising cookies or include a third-party analytics tracker. The hosting provider may process standard access logs, such as request times, IP addresses, and browser information, to deliver and secure the website.</p></section><section><h2>External resources</h2><p>Fonts are loaded from Google Fonts, and some illustrative product photography is loaded from Pexels. These providers may receive your IP address and standard request information when your browser loads their resources. Their own privacy terms apply.</p></section><section><h2>Your information</h2><p>Do not include passwords, payment details, or other sensitive information in an initial project inquiry. You can ask about, correct, or request deletion of information you have shared with us by email, subject to any applicable record-keeping obligations.</p></section><section><h2>Contact</h2><p>For questions about this notice or your information, email <a href={`mailto:${CONTACT_EMAIL}?subject=Privacy%20inquiry`}>{CONTACT_EMAIL}</a> or call <a href={CONTACT_PHONE_HREF}>{CONTACT_PHONE}</a>.</p></section></div>}
    {isTerms && <div className="legal-content"><p className="legal-updated mono">WEBSITE TERMS / 2026</p><section><h2>Using this website</h2><p>This website provides information about Devzard's services and approach. You may browse the site, use its demonstrations, and contact us about a project. Do not use it to interfere with service availability or attempt unauthorized access to any system.</p></section><section><h2>Project agreements</h2><p>Sending a project inquiry does not establish a development contract, guarantee availability, or fix a price. Scope, fees, milestones, ownership, responsibilities, and support are agreed in a separate written project agreement.</p></section><section><h2>Interactive demonstrations</h2><p>The Alwazir previews contain illustrative product, customer, transaction, and analytics data. They are demonstrations, not live client environments, and their values are not claims about client performance. Downloaded reports contain sample data only.</p></section><section><h2>Content and ownership</h2><p>Devzard's identity and original website content are presented for informational purposes. Third-party software, fonts, and photography remain subject to their respective licenses. Project-specific intellectual property is governed by the relevant project agreement.</p></section><section><h2>Availability and external services</h2><p>We aim to keep the information accurate and the website available, but neither is guaranteed at all times. External resources and email providers operate under their own terms. To the extent permitted by applicable law, information on this site is provided without a warranty of fitness for a particular purpose.</p></section><section><h2>Questions</h2><p>For questions about these terms, email <a href={`mailto:${CONTACT_EMAIL}?subject=Website%20terms`}>{CONTACT_EMAIL}</a> or call <a href={CONTACT_PHONE_HREF}>{CONTACT_PHONE}</a>.</p></section></div>}
    {!isPrivacy && !isTerms && <Reveal className="resource-contact"><div><h2>Still have a question?</h2><p>Talk to the people who will actually build your product.</p></div><SiteLink href="/#contact" className="button button-primary">Let's talk<Icon name="arrow" size={16} /></SiteLink></Reveal>}
  </div></div>;
}