import type { Service } from '../data/site';
import { useContent } from '../cms/context';
import { toService, visualFor } from '../cms/public';
import { BrandMark, Icon, Modal, Reveal, SectionLabel } from './ui';

export function ServiceVisual({ type }: { type: string }) {
  return (
    <div className={`service-visual visual-${type}`} aria-hidden="true">
      {type === 'websites' && <div className="mini-website"><div className="mini-window-bar"><span /><span /><span /><i>yourbrand.com</i></div><div className="mini-site-nav"><span className="mini-brand-square" /><span /><span /><span /></div><div className="mini-site-hero"><div><small>MAKE YOURSELF KNOWN.</small><strong>A better first<br />impression.</strong><i>Built around your business.</i><span className="mini-site-button">Get in touch <Icon name="arrow" size={6} /></span></div><div className="mini-site-image"><img src="/images/alwazir-living.jpg" alt="" loading="lazy" /></div></div><div className="mini-load-line" /></div>}
      {type === 'ecommerce' && <div className="commerce-flow"><div className="commerce-product"><div className="mini-vase"><i /></div><span>Sora ceramic vase</span><small>$48.00</small></div><span className="flow-connector"><i /></span><div className="commerce-order"><Icon name="bag" size={21} /><span>Order #2048</span><small><Icon name="check" size={9} />Confirmed</small></div></div>}
      {type === 'business' && <div className="mini-business"><div className="mini-business-heading"><span>Business overview</span><span><i className="status-dot" />Live</span></div><div className="mini-business-body"><div><small>Total revenue</small><strong>$128,450<span>+18.6%</span></strong><div className="mini-bars">{[32, 49, 40, 65, 51, 70, 62, 85, 74, 95].map((height, index) => <i key={index} style={{ height: `${height}%`, animationDelay: `${index * 60}ms` }} />)}</div></div><div className="mini-business-list"><span>Orders<strong>842</strong></span><span>Employees<strong>24</strong></span><span>Inventory<strong>96%</strong></span></div></div></div>}
      {type === 'custom' && <div className="custom-windows"><div className="mini-code-window"><div className="mini-code-title"><Icon name="code" size={10} />app.tsx<span /></div><code><span>export default</span> function App() {'{'}<br />&nbsp; <span>return</span> (<br />&nbsp; &nbsp; &lt;<b>YourNextBigThing</b><br />&nbsp; &nbsp; &nbsp; builtFor=<i>"you"</i><br />&nbsp; &nbsp; /&gt;<br />&nbsp; );<br />{'}'}</code></div><div className="mini-app-window"><div><span /><i /><i /></div><div className="mini-app-layout"><span /><section><i /><i /><div><b /><b /><b /></div></section></div><small><Icon name="check" size={8} />BUILD SUCCESSFUL</small></div></div>}
      {type === 'ai' && <div className="ai-flow"><div className="ai-flow-nodes"><span className="ai-node"><Icon name="terminal" size={20} /></span><span className="flow-connector"><i /></span><span className="ai-node ai-core"><BrandMark /></span><span className="flow-connector"><i /></span><span className="ai-node"><Icon name="check" size={20} /></span></div><div className="ai-flow-labels"><span>Request</span><span>Intelligence</span><span>Action</span></div><div className="ai-prompt"><span>&gt;</span> Find orders waiting for approval<span className="typing-cursor" /></div></div>}
    </div>
  );
}

export function Services({ onSelect }: { onSelect: (service: Service) => void }) {
  const { content } = useContent();
  const list = content.services.filter(item => item.published).sort((a, b) => a.order - b.order);
  return <section id="services" className="services-section section-space"><div className="container"><Reveal><SectionLabel>01 / What we do</SectionLabel><div className="section-intro"><h2 className="section-heading">What we build.</h2><p>Software should solve problems,<br />not create more of them.</p></div></Reveal><div className="services-grid">{list.map((item, index) => { const service = toService(item); return <Reveal key={item.id} className={`service-card service-${item.visual || item.id}`} delay={(index % 3) * 80}><div className="service-card-top"><Icon name={service.icon} size={23} /><span>{service.number}</span></div><h3>{service.title}</h3><p>{service.description}</p><ServiceVisual type={visualFor(item)} /><button className="service-open" onClick={() => onSelect(service)} aria-label={`${service.cta}, view service details`}>{service.cta}<Icon name="arrow" size={16} /></button></Reveal>; })}</div><Reveal className="services-bottom"><Icon name="terminal" size={14} /><p>From the first commit to production. Deployment and ongoing maintenance included in the conversation.</p></Reveal></div></section>;
}

export function ServiceDialog({ service, onClose, onEnquire }: { service: Service; onClose: () => void; onEnquire: (service: Service) => void }) {
  return <Modal title={service.title} onClose={onClose} className="service-dialog"><SectionLabel>DEVZARD / CAPABILITIES / {service.number}</SectionLabel><h2>{service.title}</h2><p className="modal-description">{service.detail}</p><ServiceVisual type={service.id} /><h3>What we can build</h3><ul className="service-feature-list">{service.features.map(feature => <li key={feature}><Icon name="check" size={14} />{feature}</li>)}</ul><div className="service-deliverables"><h3>What you get</h3><p>{service.deliverables}</p></div><button className="button button-primary" onClick={() => onEnquire(service)}>Let's talk about your project<Icon name="arrow" size={16} /></button><p className="fine-print">Scope, timeline, and pricing are defined together before development begins.</p></Modal>;
}